--CRIAR BANCO DE DADOS
CREATE DATABASE lojaescocosta

--TABELA CLIENTES
CREATE TABLE Clientes
(id_cliente INT NOT NULL PRIMARY KEY IDENTITY(1,1),
 nome VARCHAR (255) NOT NULL,
 cpf BIGINT UNIQUE NOT NULL, 
 rg INT UNIQUE NOT NULL,
 datanascimento VARCHAR (20) NOT NULL,
 sexo VARCHAR (15) NOT NULL,
 telefonecelular VARCHAR (25) UNIQUE NOT NULL,
 telefoneresidencial VARCHAR (25) UNIQUE NOT NULL,
 email VARCHAR (255) UNIQUE NOT NULL,
 rua VARCHAR (50) NOT NULL,
 numerocasa INT NOT NULL,
 bairro VARCHAR (50) NOT NULL,
 cep INT NOT NULL,
 estado VARCHAR (50) NOT NULL
 )

 --TABELA FORNECEDORES
 CREATE TABLE Fornecedores
(id_fornecedor INT PRIMARY KEY IDENTITY(1,1),
 nome VARCHAR (255) NOT NULL,
 cnpj BIGINT UNIQUE NOT NULL,
 datanascimento VARCHAR (20) NOT NULL,
 sexo VARCHAR (15) NOT NULL,
 telefonecelular VARCHAR (25) UNIQUE NOT NULL,
 telefoneresidencial VARCHAR (25) UNIQUE NOT NULL,
 email VARCHAR (255) UNIQUE NOT NULL,
 rua VARCHAR (50) NOT NULL,
 numerocasa INT NOT NULL,
 bairro VARCHAR (50) NOT NULL,
 cep INT NOT NULL,
 estado VARCHAR (50) NOT NULL
 );

 --TABELA PRODUTOS
 CREATE TABLE Produtos
(id_produto INT PRIMARY KEY IDENTITY(1,1),
 nome VARCHAR (255) NOT NULL,
 nome_categoria VARCHAR (255) NOT NULL,
 descricaoproduto VARCHAR (255) NOT NULL,
 nome_fornecedor VARCHAR (255) NOT NULL,
 quantidade INT NOT NULL,
 valor MONEY NOT NULL,
 valorbruto MONEY NOT NULL,
);

--TABELA CATEGORIA
 CREATE TABLE Categoria
(id_categoria INT NOT NULL PRIMARY KEY IDENTITY(1,1),
 nome VARCHAR (255) NOT NULL UNIQUE,
 )

 --TABELA USUARIO
 CREATE TABLE Usuarios
(id INT NOT NULL PRIMARY KEY IDENTITY (1,1),
 login VARCHAR (255) NOT NULL UNIQUE,
 senha VARCHAR (255) NOT NULL,
 email VARCHAR (255) NOT NULL,
 )